version: '2'
services:
    quanlyso-app:
        image: quanlyso
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://quanlyso-mysql:3306/quanlyso?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    quanlyso-mysql:
        extends:
            file: mysql.yml
            service: quanlyso-mysql
